const CURRENT_USER = 'CURRENT_USER';
const PROJECT_LIST = 'PROJECT_LIST';
const CURRENT_PROJECT = 'CURRENT_PROJECT';
const DELETE_PROJECT = 'DELETE_PROJECT';

export { CURRENT_USER, PROJECT_LIST, CURRENT_PROJECT, DELETE_PROJECT };
