const CURRENT_USER = 'CURRENT_USER';

const PROJECT_LIST = 'PROJECT_LIST';
const CURRENT_PROJECT = 'CURRENT_PROJECT';
const DELETE_PROJECT = 'DELETE_PROJECT';

const MESSAGE_LIST = 'MESSAGE_LIST';
const CURRENT_MESSAGE = 'CURRENT_MESSAGE';
const DELETE_MESSAGE = 'DELETE_MESSAGE';

export {
  CURRENT_USER, PROJECT_LIST, CURRENT_PROJECT, DELETE_PROJECT, MESSAGE_LIST, CURRENT_MESSAGE, DELETE_MESSAGE,
};
